[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 1000
via_ir = true
evm_version = "cancun"
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[profile.production]
optimizer_runs = 10000
via_ir = true

[fuzz]
runs = 1000
max_test_rejects = 100000

[rpc_endpoints]
base_mainnet = "${BASE_MAINNET_RPC}"
base_sepolia = "${BASE_SEPOLIA_RPC}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
